---
version: "3.1"
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/tobi/projects/home-assistant/ha_volume:/config
    ports:
      - 8123:8123
     # devices:
     # - /path/to/device:/path/to/device #optional
    restart: unless-stopped

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=test123
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want log times and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/Berlin
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
    volumes:
      - /home/tobi/projects/home-assistant/zwave_volume:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server

  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.20
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /home/tobi/projects/home-assistant/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=homeassistant
      - POSTGRES_USER=homeassistant
      - POSTGRES_PASSWORD=test

  influxdb:
    container_name: influxdb 
    image: influxdb:latest
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - INFLUXDB_DB=home_assistant
      - DOCKER_INFLUXDB_INIT_USERNAME=influx_user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=ha-org
      - DOCKER_INFLUXDB_INIT_BUCKET=ha-bucket
    ports:
      - 8086:8086
    volumes:
      - /home/tobi/projects/home-assistant/influxdb:/var/lib/influxdb2

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=grafana_user
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - 8125:3000
    volumes:
      - /home/tobi/projects/home-assistant/grafana:/var/lib/grafana

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 1884:1884
    volumes:
      - /home/tobi/projects/home-assistant/mosquitto/config:/mosquitto/config
      - /home/tobi/projects/home-assistant/mosquitto/data:/mosquitto/data
      - /home/tobi/projects/home-assistant/mosquitto/log:/mosquitto/log
    environment:
      - TZ: "Europe/Berlin"

  nodered:
    container_name: nodered
    image: nodered/node-red
    restart: always
    ports:
      - 1880:1880
    volumes:
      - /home/tobi/projects/home-assistant/nodered:/data
    depends_on:
      - home-assistant
      - mosquitto
    environment:
      - TZ: "Europe/Berlin"
