esphome:
  name: esphome-relays
  friendly_name: relay-switches
  min_version: 2024.11.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino


switch:
  - platform: gpio
    name: "Off_Peak"
    pin: GPIO16
    id: relay1
  - platform: gpio
    name: "Solar_Surplus"
    pin: GPIO17
    id: relay2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none
